name: Publish as scully on GitHub pages.

on:
  push:
    branches:
      - cleaning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: ${{ secrets.DEPLOY_BRANCH }}
